### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by SlackOps01** [cyber-turtle/Weather-App-iOS-16.4#1]
How you doing now?

**Comment by SlackOps01** [comment]
Better answer so I can close the issue

**Comment by cyber-turtle** [comment]
im here now boss

**Comment by cyber-turtle** [comment]
you know we aren't online 24/7 here

**Comment by cyber-turtle** [comment]
no vex

**Comment by SlackOps01** [comment]
I get and I see you're still adding files to your repo via upload,use git cli or regular git on your terminal or even a git extension on vscode or something believe me doing an upload is going to get tiring and you won't be able to keep track of meaning changes

**Comment by cyber-turtle** [comment]
omo,thanks let me try to learn how to use it

**Comment by SlackOps01** [comment]
Guy I'm starting to lean a bit more into IT infrastructure/Dev Ops
